import React, { useState, useEffect } from 'react';
import { Copy, Check, MessageSquare, Send, Globe, AlertCircle, Sparkles } from 'lucide-react';
import type { EmergencyAnalysis } from '../types/Emergency';
import { translateEmergencyText } from '../services/gemini';

interface SOSGeneratorViewProps {
  analysis: EmergencyAnalysis;
  apiKey?: string;
}

export const SOSGeneratorView: React.FC<SOSGeneratorViewProps> = ({ analysis, apiKey }) => {
  const [selectedLanguage, setSelectedLanguage] = useState('English');
  const [sosText, setSosText] = useState('');
  const [copied, setCopied] = useState(false);
  const [isTranslating, setIsTranslating] = useState(false);

  const baseSosTemplate = `🚨 EMERGENCY ALERT! 🚨
Incident: ${analysis.title}
Location: ${analysis.locationName}
GPS Link: https://maps.google.com/?q=${analysis.coordinates.lat},${analysis.coordinates.lng}

Severity: ${analysis.severity} (${analysis.confidence}% AI Confidence)
Victims: ${analysis.peopleDetected} People Detected | ${analysis.estimatedInjuries} Injured
Active Hazards: ${analysis.hazards.join(', ')}

IMMEDIATE ACTION NEEDED:
${analysis.immediateActions.map((a, i) => `${i + 1}. ${a}`).join('\n')}

Generated by CrisisMind AI Emergency Platform.`;

  useEffect(() => {
    let isMounted = true;
    const updateSOS = async () => {
      if (selectedLanguage === 'English') {
        setSosText(baseSosTemplate);
        return;
      }

      setIsTranslating(true);
      const translated = await translateEmergencyText(baseSosTemplate, selectedLanguage, apiKey);
      if (isMounted) {
        setSosText(translated);
        setIsTranslating(false);
      }
    };

    updateSOS();
    return () => {
      isMounted = false;
    };
  }, [selectedLanguage, analysis, apiKey]);

  const handleCopy = () => {
    navigator.clipboard.writeText(sosText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleWhatsApp = () => {
    const url = `https://api.whatsapp.com/send?text=${encodeURIComponent(sosText)}`;
    window.open(url, '_blank');
  };

  const handleSMS = () => {
    const url = `sms:?body=${encodeURIComponent(sosText)}`;
    window.open(url, '_blank');
  };

  const languages = [
    { code: 'en', name: 'English' },
    { code: 'hi', name: 'Hindi' },
    { code: 'mr', name: 'Marathi' },
    { code: 'gu', name: 'Gujarati' },
    { code: 'ta', name: 'Tamil' },
    { code: 'te', name: 'Telugu' },
  ];

  return (
    <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 space-y-6">
      {/* Header */}
      <div className="text-center space-y-2">
        <div className="inline-flex items-center space-x-2 rounded-full border border-red-500/30 bg-red-500/10 px-4 py-1 text-xs font-bold text-red-400">
          <AlertCircle className="h-4 w-4" />
          <span>Multilingual SOS Alert Dispatcher</span>
        </div>
        <h1 className="text-3xl font-extrabold text-white">Generate SOS Broadcast</h1>
        <p className="text-xs text-slate-300">
          One-tap multi-channel emergency message formatted with GPS coordinates, hazards, and Gemini translation.
        </p>
      </div>

      {/* Main Glass Card */}
      <div className="glass-card p-6 border border-white/15 shadow-2xl space-y-6">
        {/* Language Selector Toolbar */}
        <div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-4">
          <div className="flex items-center space-x-2 text-xs font-bold text-slate-300">
            <Globe className="h-4 w-4 text-blue-400" />
            <span>Target Language:</span>
          </div>

          <div className="flex flex-wrap gap-1.5">
            {languages.map((lang) => (
              <button
                key={lang.code}
                onClick={() => setSelectedLanguage(lang.name)}
                className={`rounded-xl px-3 py-1.5 text-xs font-bold transition ${
                  selectedLanguage === lang.name
                    ? 'bg-blue-600 text-white shadow-md shadow-blue-600/30'
                    : 'bg-slate-900/80 text-slate-400 hover:bg-slate-800 hover:text-white'
                }`}
              >
                {lang.name}
              </button>
            ))}
          </div>
        </div>

        {/* SOS Textarea */}
        <div className="relative">
          {isTranslating && (
            <div className="absolute inset-0 z-10 flex items-center justify-center rounded-2xl bg-slate-950/80 backdrop-blur-sm">
              <div className="flex items-center space-x-2 text-xs font-bold text-blue-400">
                <Sparkles className="h-4 w-4 animate-spin-slow" />
                <span>Translating via Gemini API...</span>
              </div>
            </div>
          )}

          <textarea
            value={sosText}
            onChange={(e) => setSosText(e.target.value)}
            rows={10}
            className="w-full rounded-2xl border border-white/10 bg-slate-950/80 p-4 font-mono text-xs text-slate-100 leading-relaxed focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
          />
        </div>

        {/* Action Buttons Row */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          {/* Copy Button */}
          <button
            onClick={handleCopy}
            className="flex items-center justify-center space-x-2 rounded-2xl border border-white/15 bg-slate-800 py-3 text-xs font-bold text-slate-200 transition hover:bg-slate-700 hover:text-white"
          >
            {copied ? <Check className="h-4 w-4 text-emerald-400" /> : <Copy className="h-4 w-4 text-blue-400" />}
            <span>{copied ? 'Copied to Clipboard!' : 'Copy SOS Text'}</span>
          </button>

          {/* WhatsApp Button */}
          <button
            onClick={handleWhatsApp}
            className="flex items-center justify-center space-x-2 rounded-2xl bg-emerald-600 py-3 text-xs font-bold text-white shadow-lg shadow-emerald-600/30 transition hover:bg-emerald-500"
          >
            <MessageSquare className="h-4 w-4" />
            <span>Share on WhatsApp</span>
          </button>

          {/* SMS Button */}
          <button
            onClick={handleSMS}
            className="flex items-center justify-center space-x-2 rounded-2xl bg-gradient-to-r from-blue-600 to-indigo-600 py-3 text-xs font-bold text-white shadow-lg shadow-blue-500/30 transition hover:from-blue-500 hover:to-indigo-500"
          >
            <Send className="h-4 w-4" />
            <span>Send via SMS</span>
          </button>
        </div>
      </div>
    </div>
  );
};
